"use client";
import {useRef} from "react";
import {useInvoiceStore} from "@/store/useInvoiceStore";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Label} from "@/components/ui/label"; import {Textarea} from "@/components/ui/textarea";
import {Plus,Trash2,RotateCcw,Upload} from "lucide-react";
import {LOCALES,t} from "@/lib/i18n";
const CURRENCIES=["USD","EUR","GBP","PKR","AED","INR","CAD","AUD","JPY","CHF","SAR","CNY","SGD","HKD","NZD","QAR","KWD","BHD","OMR","TRY","RUB","ZAR","MYR","SEK","NOK","DKK","PLN"];
const DEFAULT_LABELS={invoice:"Invoice",from:"From",billTo:"Bill to",description:"Description",quantity:"Qty",rate:"Rate",amount:"Amount",subtotal:"Subtotal",discount:"Discount",tax:"Tax",total:"Total"};
const LABEL_KEYS=Object.keys(DEFAULT_LABELS) as (keyof typeof DEFAULT_LABELS)[];
const num=(value:string)=>{const n=Number(value);return Number.isFinite(n)?Math.max(0,n):0};
export function InvoiceForm(){
 const invoice=useInvoiceStore(s=>s.invoice),setField=useInvoiceStore(s=>s.setField),setParty=useInvoiceStore(s=>s.setParty),addItem=useInvoiceStore(s=>s.addItem),updateItem=useInvoiceStore(s=>s.updateItem),removeItem=useInvoiceStore(s=>s.removeItem),setGlobalDiscount=useInvoiceStore(s=>s.setGlobalDiscount),setTheme=useInvoiceStore(s=>s.setTheme),setLabels=useInvoiceStore(s=>s.setLabels);
 const fileRef=useRef<HTMLInputElement>(null); const x=(k:any)=>t(invoice.language,k);
 function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){alert("Please choose an image smaller than 2 MB.");return;}const r=new FileReader();r.onload=()=>setTheme({logoDataUrl:r.result as string});r.readAsDataURL(f);}
 return <div className="space-y-5">
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold">{x("invoiceNumber")}</h3><p className="text-xs text-slate-500">Basic details for this invoice.</p></div><select aria-label={x("language")} className="h-9 rounded-md border bg-white px-3 text-sm" value={invoice.language} onChange={e=>setField("language",e.target.value)}>{Object.entries(LOCALES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></div>
   <div className="grid gap-4 sm:grid-cols-4"><div><Label>{x("invoiceNumber")}</Label><Input value={invoice.invoiceNumber} onChange={e=>setField("invoiceNumber",e.target.value)}/></div><div><Label>{x("currency")}</Label><select className="h-9 w-full rounded-md border bg-white px-3 text-sm" value={invoice.currency} onChange={e=>setField("currency",e.target.value)}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></div><div><Label>{x("issueDate")}</Label><Input type="date" value={invoice.issueDate} onChange={e=>setField("issueDate",e.target.value)}/></div><div><Label>{x("dueDate")}</Label><Input type="date" value={invoice.dueDate} onChange={e=>setField("dueDate",e.target.value)}/></div></div>
  </section>
  <section className="grid gap-5 sm:grid-cols-2"><Party title={x("from")} p={invoice.sender} x={x} onChange={u=>setParty("sender",u)}/><Party title={x("billTo")} p={invoice.recipient} x={x} onChange={u=>setParty("recipient",u)}/></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3"><h3 className="font-semibold">{x("items")}</h3><p className="text-xs text-slate-500">Add products or services. Amounts update instantly as you type.</p></div>
   <div className="hidden grid-cols-12 gap-2 px-1 pb-2 text-xs font-medium text-slate-400 sm:grid"><div className="col-span-5">{x("description")}</div><div className="col-span-2">{x("quantity")}</div><div className="col-span-2">{x("rate")}</div><div className="col-span-2 text-right">{x("amount")}</div></div>
   <div className="space-y-3">{invoice.items.map(item=><div key={item.id} className="grid grid-cols-12 gap-2 rounded-xl border bg-slate-50/60 p-3"><Input className="col-span-12 sm:col-span-5" aria-label={x("description")} placeholder={x("description")} value={item.description} onChange={e=>updateItem(item.id,{description:e.target.value})}/><Input className="col-span-4 sm:col-span-2 no-spinner" inputMode="decimal" type="text" aria-label={x("quantity")} placeholder="1" value={item.quantity} onChange={e=>updateItem(item.id,{quantity:num(e.target.value)})}/><Input className="col-span-4 sm:col-span-2 no-spinner" inputMode="decimal" type="text" aria-label={x("rate")} placeholder="0.00" value={item.rate} onChange={e=>updateItem(item.id,{rate:num(e.target.value)})}/><select className="col-span-4 h-9 rounded-md border bg-white px-2 text-sm sm:col-span-2" value={item.pricingType} onChange={e=>updateItem(item.id,{pricingType:e.target.value as any})}><option value="quantity">{x("standard")}</option><option value="percentage">{x("percentage")}</option></select><Button type="button" variant="ghost" size="icon" className="col-span-1" onClick={()=>removeItem(item.id)} aria-label={x("remove")}><Trash2 className="h-4 w-4"/></Button>{item.pricingType==="percentage"&&<div className="col-span-12 sm:col-start-7 sm:col-span-2"><Input className="no-spinner" inputMode="decimal" type="text" aria-label={x("commission")} placeholder="%" value={item.commissionRate} onChange={e=>updateItem(item.id,{commissionRate:num(e.target.value)})}/></div>}</div>)}</div>
   <Button type="button" variant="outline" size="sm" className="mt-4" onClick={addItem}><Plus className="mr-1 h-4 w-4"/>{x("addItem")}</Button>
  </section>
  <section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-3"><div><Label>{x("taxLabel")}</Label><Input value={invoice.taxLabel} onChange={e=>setField("taxLabel",e.target.value)}/></div><div><Label>{x("taxRate")}</Label><Input className="no-spinner" inputMode="decimal" type="text" value={invoice.taxRate} onChange={e=>setField("taxRate",num(e.target.value))}/></div><div><Label>{x("discount")}</Label><Input className="no-spinner" inputMode="decimal" type="text" value={invoice.globalDiscount.value} onChange={e=>setGlobalDiscount({type:"percent",value:num(e.target.value)})}/></div></section>
  <details className="rounded-2xl border bg-white shadow-sm"><summary className="cursor-pointer list-none p-5 font-semibold">{x("customizeLabels")}</summary><div className="border-t p-5"><p className="mb-4 text-xs text-slate-500">{x("customizeHint")}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{LABEL_KEYS.map(k=><div key={k}><Label>{(x as any)(k==="invoice"?"invoice":k==="quantity"?"qty":k)}</Label><Input value={(invoice.labels as any)[k]} onChange={e=>setLabels({[k]:e.target.value} as any)}/></div>)}</div><Button type="button" variant="ghost" size="sm" className="mt-4" onClick={()=>setLabels(DEFAULT_LABELS)}><RotateCcw className="mr-1 h-4 w-4"/>{x("resetLabels")}</Button></div></details>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><div><Label>{x("logo")}</Label><input ref={fileRef} className="hidden" type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={upload}/><Button type="button" variant="outline" onClick={()=>fileRef.current?.click()}><Upload className="mr-2 h-4 w-4"/>Upload logo</Button>{invoice.theme.logoDataUrl&&<Button type="button" variant="ghost" size="sm" className="ml-2" onClick={()=>setTheme({logoDataUrl:null})}>Remove</Button>}<p className="mt-1 text-xs text-slate-400">PNG, JPG or SVG · max 2 MB</p></div><div><Label>{x("accentColor")}</Label><Input type="color" className="h-9 p-1" value={invoice.theme.accentColor} onChange={e=>setTheme({accentColor:e.target.value})}/></div></div></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><Label>{x("notes")}</Label><Textarea rows={4} placeholder={x("notesPlaceholder")} value={invoice.notes} onChange={e=>setField("notes",e.target.value)}/></section>
 </div>
}
function Party({title,p,x,onChange}:{title:string;p:any;x:(k:any)=>string;onChange:(u:any)=>void}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="mb-3 font-semibold">{title}</h3><div className="space-y-2"><Input placeholder={x("name")} value={p.name} onChange={e=>onChange({name:e.target.value})}/><Textarea placeholder={x("address")} rows={2} value={p.address} onChange={e=>onChange({address:e.target.value})}/><Input placeholder={x("email")} type="email" value={p.email} onChange={e=>onChange({email:e.target.value})}/><Input placeholder={x("phone")} value={p.phone} onChange={e=>onChange({phone:e.target.value})}/></div></div>}
