import Link from "next/link";
import { InvoiceBuilder } from "@/components/invoice/InvoiceBuilder";
import { resources } from "@/lib/resources";

export default function Home(){
 return <>
  <section className="hero"><div className="hero-inner"><span className="eyebrow">100% free · no account · browser-based</span><h1>Create a professional invoice in minutes.</h1><p>InvoPlanet is a simple online invoice maker for freelancers, small businesses and teams. Add your details, enter your items, review the total and download a clean PDF.</p><div className="hero-actions"><a className="primary-link" href="#invoice-maker">Create an invoice</a><Link className="secondary-link" href="/how-to-use">How it works</Link></div><div className="trust-row"><span>Multiple currencies</span><span>7 languages</span><span>Taxes & discounts</span><span>Commission pricing</span><span>PDF export</span></div></div></section>
  <InvoiceBuilder/>
  <section className="content-wrap"><h2>A free invoice tool built for real-world work</h2><p className="lead">Different businesses bill in different ways. InvoPlanet keeps the editor flexible without making the workflow complicated.</p><div className="feature-grid"><div className="feature-card"><h3>Simple by default</h3><p>Start with only the information needed for a clear invoice. Add more detail only when your transaction needs it.</p></div><div className="feature-card"><h3>Flexible pricing</h3><p>Bill by quantity, rate, hours, fixed amounts or percentage-based commissions, then see the calculation update as you type.</p></div><div className="feature-card"><h3>International-ready</h3><p>Choose a language and currency that fit your customer. Urdu and Arabic layouts support right-to-left text.</p></div></div></section>
  <section className="content-wrap"><h2>Learn more about invoicing</h2><p className="lead">Our free guides explain practical invoicing topics in plain language. They are educational resources, not legal or tax advice.</p><div className="article-list">{resources.slice(0,6).map(r=><Link className="article-card" key={r.slug} href={`/resources/${r.slug}`}><h3>{r.title}</h3><p>{r.description}</p></Link>)}</div><div className="hero-actions" style={{justifyContent:"flex-start"}}><Link className="secondary-link" href="/resources">View all guides</Link></div></section>
  <section className="content-wrap"><h2>Frequently asked questions</h2><div className="faq-list"><details><summary>Is InvoPlanet free?</summary><p>Yes. The invoice maker is designed to be free to use without a subscription or account.</p></details><details><summary>Does InvoPlanet store my invoice?</summary><p>The current editor does not automatically save invoice drafts or invoice history. The invoice is created in the browser and exported from the page.</p></details><details><summary>Can I use it for my business?</summary><p>It can be used for many common business models, but you are responsible for checking the tax, invoicing and record-keeping rules that apply to your business and country.</p></details></div></section>
 </>
}
